// ===== Interfaces (Data Types) =====
interface Word {
  text: string;
  clue: string;
  startX: number;
  startY: number;
  direction: "across" | "down";
  number: number;
}

// Koordinates von Wörtern im Raster
export const WORDS_TEMPLATE: Word[] = [
  // ===== HORIZONTAL WORDS (ACROSS) =====
  {
    text: "ASYNC",
    clue: "Asynchronous programming keyword",
    startX: 2,
    startY: 1,
    direction: "across",
    number: 1,
  },
  {
    text: "WHILE",
    clue: "Loop that continues based on condition",
    startX: 3,
    startY: 2,
    direction: "across",
    number: 2,
  },
  {
    text: "VAR",
    clue: "Variable declaration (old style)",
    startX: 1,
    startY: 3,
    direction: "across",
    number: 3,
  },
  {
    text: "SCOPE",
    clue: "Variable visibility area",
    startX: 4,
    startY: 3,
    direction: "across",
    number: 4,
  },
  {
    text: "THIS",
    clue: "Context reference keyword",
    startX: 9,
    startY: 3,
    direction: "across",
    number: 5,
  },
  {
    text: "HOISTING",
    clue: "Variable lifting behavior",
    startX: 3,
    startY: 4,
    direction: "across",
    number: 6,
  },
  {
    text: "DOM",
    clue: "Document Object Model",
    startX: 11,
    startY: 4,
    direction: "across",
    number: 7,
  },
  {
    text: "LET",
    clue: "Block-scoped variable declaration",
    startX: 0,
    startY: 5,
    direction: "across",
    number: 8,
  },
  {
    text: "FUNCTION",
    clue: "Reusable code block",
    startX: 5,
    startY: 5,
    direction: "across",
    number: 9,
  },
  {
    text: "SHIFT",
    clue: "Remove first element from array",
    startX: 0,
    startY: 6,
    direction: "across",
    number: 10,
  },
  {
    text: "EVENT",
    clue: "User interaction or system occurrence",
    startX: 6,
    startY: 7,
    direction: "across",
    number: 11,
  },
  {
    text: "RETURN",
    clue: "Send value back from function",
    startX: 3,
    startY: 8,
    direction: "across",
    number: 12,
  },
  {
    text: "UNMOUNT",
    clue: "Remove component from DOM",
    startX: 9,
    startY: 8,
    direction: "across",
    number: 13,
  },
  {
    text: "REDUCE",
    clue: "Array method to single value",
    startX: 0,
    startY: 9,
    direction: "across",
    number: 14,
  },
  {
    text: "FOR",
    clue: "Basic loop construct",
    startX: 13,
    startY: 9,
    direction: "across",
    number: 15,
  },
  {
    text: "NEW",
    clue: "Create object instance",
    startX: 11,
    startY: 10,
    direction: "across",
    number: 16,
  },
  {
    text: "FETCH",
    clue: "Modern HTTP request method",
    startX: 4,
    startY: 11,
    direction: "across",
    number: 17,
  },
  {
    text: "TYPE",
    clue: "Data classification",
    startX: 11,
    startY: 11,
    direction: "across",
    number: 18,
  },

  // ===== VERTICAL WORDS (DOWN) =====
  {
    text: "AWAIT",
    clue: "Wait for promise resolution",
    startX: 2,
    startY: 1,
    direction: "down",
    number: 19,
  },
  {
    text: "CLOSURE",
    clue: "Function with access to outer scope",
    startX: 6,
    startY: 1,
    direction: "down",
    number: 20,
  },
  {
    text: "JSON",
    clue: "JavaScript Object Notation",
    startX: 12,
    startY: 2,
    direction: "down",
    number: 21,
  },
  {
    text: "SORT",
    clue: "Arrange array elements in order",
    startX: 4,
    startY: 3,
    direction: "down",
    number: 22,
  },
  {
    text: "FILTER",
    clue: "Array method to select elements",
    startX: 5,
    startY: 5,
    direction: "down",
    number: 23,
  },
  {
    text: "SEARCH",
    clue: "Find data or elements",
    startX: 0,
    startY: 6,
    direction: "down",
    number: 24,
  },
  {
    text: "LENGTH",
    clue: "Property showing array size",
    startX: 8,
    startY: 6,
    direction: "down",
    number: 25,
  },
  {
    text: "BREAK",
    clue: "Exit loop or switch early",
    startX: 1,
    startY: 7,
    direction: "down",
    number: 26,
  },
  {
    text: "NULL",
    clue: "Intentional empty value",
    startX: 9,
    startY: 7,
    direction: "down",
    number: 27,
  },
  {
    text: "NODE",
    clue: "Element in DOM tree",
    startX: 14,
    startY: 8,
    direction: "down",
    number: 28,
  },
  {
    text: "DOCUMENT",
    clue: "HTML page object",
    startX: 11,
    startY: 4,
    direction: "down",
    number: 29,
  },
];
